# Generated by Django 5.1.4 on 2025-04-04 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_wpmresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wpmresult',
            name='accuracy',
        ),
    ]
