# Generated by Django 5.1.4 on 2025-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_wpmresult_accuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpmresult',
            name='time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
