# Generated by Django 5.1.4 on 2025-04-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_text_content_wpmresult'),
        ('api', '0005_wpmresult_time'),
    ]

    operations = [
    ]
