# Generated by Django 5.1.4 on 2025-06-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20250425_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='wpmresult',
            name='accuracy',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
